%% Config
setup;
netID= 'featmapVlad';
paths= yul_localPaths();
dbTrain= yul_get_ucf101(paths, 'trainlist01.txt');
dbVal= yul_get_ucf101(paths, 'testlist01.txt');
lr= 0.1;
net=[];

%% Cannot modified
dbFm_train = yul_get_dbFm(dbTrain, paths);
dbFm_test = yul_get_dbFm(dbVal, paths);
load('snapshot/net0_pool5.mat');
sessionID= yul_train_from_featmap(dbFm_train, dbFm_test, net, ...
    'netID', netID, ...
    'method', 'vlad_preL2_intra', ...
    'learningRate', lr, ...
    'doDraw', true, ...
    'batchSize', 16, ...
    'nEpoch', 50, ...
    'layerName', 'conv5_3' ...
    );